apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    app: web
spec:
  containers:
  - image: androidraddik/nginx_static_app:1.2
    name: web
    livenessProbe:
      tcpSocket:
        port: 8000
    readinessProbe:
      httpGet:
        path: /index.html
        port: 80
    volumeMounts:
    - name: app
      mountPath: /app
  initContainers:
  - image: busybox:1.31
    name: init-web
    command: ['sh', '-c', 'wget -O- https://tinyurl.com/otus-k8s-intro | sh']
    volumeMounts:
    - name: app
      mountPath: /app
  volumes:
  - name: app
    emptyDir: {}